server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true

      routes[0]:
        id: posts-get
        uri: lb://posts-service
        predicates[0]: Path=/posts-service/posts
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: RewritePath=/posts-service/(?<segment>.*), /$\{segment}