server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true

      routes[0]:
        id: users-status-check-get
        uri: lb://users-service
        predicates[0]: Path=/users-service/status/check
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: RewritePath=/users-service/(?<segment>.*), /$\{segment}

      routes[1]:
        id: users-register-post
        uri: lb://users-service
        predicates[0]: Path=/users-service/register
        predicates[1]: Method=POST
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: RewritePath=/users-service/(?<segment>.*), /$\{segment}

      routes[2]:
        id: users-login-post
        uri: lb://users-service
        predicates[0]: Path=/users-service/login
        predicates[1]: Method=POST
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: RewritePath=/users-service/(?<segment>.*), /$\{segment}

      routes[3]:
        id: users-userid-get
        uri: lb://users-service
        predicates[0]: Path=/users-service/users/{user-id}
        predicates[1]: Method=GET
#        predicates[2]: Header=Authorization, Bearer (.*) // it won't send the request if there is no token, but it returns a 404
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: RewritePath=/users-service/(?<segment>.*), /$\{segment}
        filters[2]: AuthorizationHeaderFilter

      routes[4]:
        id: posts-status-check-get
        uri: lb://posts-service
        predicates[0]: Path=/posts-service/status/check
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: RewritePath=/posts-service/(?<segment>.*), /$\{segment}

      routes[5]:
        id: posts-get
        uri: lb://posts-service
        predicates[0]: Path=/posts-service/posts
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: RewritePath=/posts-service/(?<segment>.*), /$\{segment}

logging:
  level:
    org:
      springframework:
        web: DEBUG

app:
  token:
    secret: RANDOM_SECRET_FOR_JWT
    issuer: "users-service"
