server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: users-service

  r2dbc:
    url: r2dbc:mysql://localhost:3306
    name: micro-services-example-users-service
    username: root
    password: root
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 15s
      validation-query: SELECT 1
    properties:
      connect-timeout: 10
      ssl: false
      max-create-connection-time: 3
      max-acquire-time: 5
      max-life-time: 15
  flyway:
    url: jdbc:mysql://localhost:3306/micro-services-example-users-service
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    cleanDisabled: false

logging:
  level:
    org:
      springframework:
        web: DEBUG

app:
  token:
    secret: RANDOM_SECRET_FOR_JWT
    issuer: ${spring.application.name}
    expires-minute: 60 * 8
